language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_failure: true
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.3
          env: SYMFONY_VERSION=^4.3
        - php: 7.3
          env: SYMFONY_VERSION=^5.0
    allow_failures:
        - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || true
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: ./vendor/bin/phpunit --coverage-text
