name: PHPUnit

on:
  pull_request:

jobs:

  tests:
    name: Tests
    runs-on: Ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          # Lowest Deps
          - php: 8.1
            symfony-require: 5.4.*
          # LTS with latest (supported) stable PHP
          - php: 8.2
            symfony-require: 5.4.*
          # Active release
          - php: latest
            symfony-require: 6.3.*
          - php: latest
            symfony-require: 7.0.*
          # Development release
          - php: nightly
            symfony-require: 7.0.*@dev
            stability: dev
            continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      - name: Configure Composer minimum stability
        if: matrix.stability
        run: composer config minimum-stability ${{ matrix.stability }}

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: composer update --prefer-dist

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
