name: PHPUnit

on:
  push:
  pull_request:

jobs:

  tests:
    name: Tests
    runs-on: Ubuntu-20.04

    strategy:
      matrix:
        include:
          - php: '7.4'
          - php: '8.0'
          - php: '8.1'
            mode: experimental

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
